---
- name: Login to Azure CLI as service principal
  ansible.builtin.command: >
    az login --service-principal -u "{{ azure.service_principal_id }}" -p "{{ azure.service_principal_secret }}" --tenant "{{ azure.tenant_id }}"
  register: az_cli_login
  ignore_errors: true
  failed_when: (az_cli_login.rc not in [0, 16])
  changed_when: false

- name: Create the default connectivity endpoint on Linux endpoint
  ansible.builtin.command: >
    az rest --method put --uri https://management.azure.com/subscriptions/{{ azure.subscription_id }}/resourceGroups/{{ azure.resource_group }}/providers/Microsoft.HybridCompute/machines/{{ ansible_hostname }}/providers/Microsoft.HybridConnectivity/endpoints/default?api-version=2023-03-15 --body '{\"properties\": {\"type\": \"default\"}}'
  register: arc_default_connection
  ignore_errors: true
  failed_when: (arc_default_connection.rc not in [0, 16])
  changed_when: false

- name: Enable functionality on Arc Linux endpoint
  ansible.builtin.command: >
    az rest --method put --uri https://management.azure.com/subscriptions/{{ azure.subscription_id }}/resourceGroups/{{ azure.resource_group }}/providers/Microsoft.HybridCompute/machines/{{ ansible_hostname }}/providers/Microsoft.HybridConnectivity/endpoints/default/serviceconfigurations/SSH?api-version=2023-03-15 --body "{\"properties\": {\"serviceName\": \"SSH\", \"port\": 22}}"
  register: arc_ssh_functional
  changed_when: arc_ssh_functional.rc != 0
  failed_when: ("ERROR" in arc_ssh_functional.stderr)
