---
- name: Install Arc for Linux and connect host to azure
  vars_file:
    - ./group_vars/all.yml
  tasks:
    - name: Download the installation package
      become: true
      get_url:
        url: https://aka.ms/azcmagent
        dest: ~/install_linux_azcmagent.sh
        mode: '700'
    - name: Install the hybrid agent with Proxy setup
      shell: azcmagent -v >/dev/null 2>&1 || ~/install_linux_azcmagent.sh --proxy "'{{ local.proxy }}'"
      become: true
      when: proxy is defined
    - name: Install the hybrid agent without proxy
      shell: azcmagent -v >/dev/null 2>&1 || ~/install_linux_azcmagent.sh
      become: true
      when: proxy is undefined
    - name: Run connect command
      become: true
      shell: azcmagent show | grep -q -i "Disconnected" && azcmagent connect --service-principal-id '{{ azure.service_principal_id }}'  --service-principal-secret '{{ azure.service_principal_secret }}' --resource-group '{{ azure.resource_group }}' --tenant-id '{{ azure.tenant_id }}' --location '{{ azure.location }}' --subscription-id '{{ azure.subscription_id }}' --tags 'Project=jumpstart_azure_arc_servers' --correlation-id 'd009f5dd-dba8-4ac7-bac9-b54ef3a6671a' || echo 'Machine already connected'
