---
- name: Check if Connected Machine Agent has already been downloaded
  ansible.builtin.stat:
    path: /usr/bin/azcmagent
    get_attributes: false
    get_checksum: false
  register: arc_azcmagent_lnx_downloaded

- name: Download the Arc Connected Machine Agent on Linux Servers
  become: true
  ansible.builtin.get_url:
    url: https://aka.ms/azcmagent
    dest: /tmp/install_linux_azcmagent.sh
    mode: "700"
  when:
    - (not arc_azcmagent_lnx_downloaded.stat.exists)

- name: Install the Connected Machine Agent on Linux Servers
  become: true
  ansible.builtin.command: >
    bash /tmp/install_linux_azcmagent.sh
  register: arc_azcmagent_lnx_install
  when:
    - (not arc_azcmagent_lnx_downloaded.stat.exists)
  failed_when: (arc_azcmagent_lnx_install.rc not in [0, 16])
  changed_when: (arc_azcmagent_lnx_install.rc in [0, 16])

- name: Check if the Connected Machine Agent has already been connected to Azure
  become: true
  ansible.builtin.command: >
    azcmagent check
  register: arc_azcmagent_lnx_connected
  ignore_errors: true
  failed_when: (arc_azcmagent_lnx_connected.rc not in [0, 16])
  changed_when: false

- name: Connect the Connected Machine Agent on Linux to Azure Arc
  become: true
  ansible.builtin.command: >
    azcmagent connect --service-principal-id "{{ azure.service_principal_id }}" --service-principal-secret "{{ azure.service_principal_secret }}" --resource-group "{{ azure.resource_group }}" --tenant-id "{{ azure.tenant_id }}" --location "{{ azure.location }}" --subscription-id "{{ azure.subscription_id }}"
  register: arc_azcmagent_lnx_connect
  when:
    - (arc_azcmagent_lnx_connected.rc is defined and arc_azcmagent_lnx_connected.rc != 0)
  failed_when: (arc_azcmagent_lnx_connect.rc not in [0, 16])
  changed_when: (arc_azcmagent_lnx_connect.rc in [0, 16])

- name: Install the ConnectedMachine extension on Linux endpoints
  ansible.builtin.command:
    az extension add --name connectedmachine
  register: arc_connectedmachine
  changed_when: arc_connectedmachine.rc != 0
  failed_when: ("ERROR" in arc_connectedmachine.stderr)
