#cloud-config

package_update: true
package_upgrade: true
packages:
  - git
  - python3-pip

users:
- name: ansible
  gecos: Ansible User
  shell: /bin/bash
  groups: users,admin,wheel
  sudo: ALL=(ALL) NOPASSWD:ALL

ansible:
  install_method: pip
  package_name: ansible
  run_user: ansible

write_files:
  - path: /home/ansible/.ssh/id_rsa
    owner: ansible:ansible
    permissions: 0o600
    defer: true
    encoding: base64
    content: |
      < id_rsa content here>