---
- name: Provision Azure Arc connected machine agents on Linux servers
  vars_files:
    - ./group_vars/all.yml
  hosts: tag_AppGroup_LinuxFarm
  tasks:
    - name: Install Arc Agent and Entra ID extension on Linux machines
      block:
        - name: Install Azure CLI on Linux machines
          ansible.builtin.include_tasks:
            file: ./tasks/azure_cli.yml
          when: ansible_system == 'Linux'
        - name: Install Arc Agent on Linux machines
          ansible.builtin.include_tasks:
            file: ./tasks/linux_arc.yml
          when: ansible_system == 'Linux'
