---
- name: Provision Entra ID auth extension on Linux servers
  vars_files:
    - ./group_vars/all.yml
  hosts: tag_AppGroup_LinuxFarm
  tasks:
    - name: Install and enable the Entra ID extension on Linux machines
      block:
        - name: Install and enable Entra ID extension
          ansible.builtin.include_tasks:
            file: ./tasks/enable_entra.yml
          when: ansible_system == 'Linux'
